'users.gender' = 'masculine personal'
'user.gender' = 'masculine personal'
'group.gender' = 'feminine'
'permission.gender' = 'neuter'
'session.gender' = 'feminine'
'site.gender' = 'feminine'
'redirect.gender' = 'neuter'
'flat page.gender' = 'feminine'
'log entry.gender' = 'masculine inanimate'
'content type.gender' = 'masculine inanimate'

'users.accusative' = 'użytkowników'
'user.accusative' = 'użytkownika'
'users.genitive' = 'użytkowników'
'group.accusative' = 'grupę'
'groups.genitive' = 'grup'
'groups.accusative' = 'grupy'
'permissions.genitive' = 'uprawnień'
'session.accusative' = 'sesję'
'sessions.genitive' = 'sesji'
'site.accusative' = 'stronę'
'sites.genitive' = 'stron'
'redirects.genitive' = 'przekierowań'
'flat page.accusative' = 'stronę statyczną'
'flat pages.genitive' = 'stron statycznych'
'log entries.genitive' = 'logów'
'content types.genitive' = 'typów zawartości'
'user.genitive' = 'użytkownika'
'group.genitive' = 'grupy'
'permission.genitive' = 'uprawnienia'
'session.genitive' = 'sesji'
'site.genitive' = 'strony'
'redirect.genitive' = 'przekierowania'
'flat page.genitive' = 'strony statycznej'
'log entry.genitive' = 'logu'
'content type.genitive' = 'typu zawartości'
'redirect.accusative' = 'przekierowanie'

'Select %s' = 'Wybierz %(.accusative)s'
'Select %s to change' = 'Wybierz %(.accusative)s do zmiany'
'Select %s to view' = 'Wybierz %(.accusative)s do obejrzenia'
'Add %(name)s' = 'Dodaj %(name.accusative)s'
'Cannot delete %(name)s' = 'Nie można usunąć %(name.genitive)s'
'Added {name} “{object}”.' = 'Dodano {name.accusative} „{object}”.'
'Changed {fields} for {name} “{object}”.' = 'Zmodyfikowano {fields} {name.genitive} „{object}”'
'Deleted {name} “{object}”.' = 'Usunięto {name.accusative} „{object}”.'
'Add %s' = 'Dodaj %(.accusative)s'
'Change %s' = 'Zmień %(.accusative)s'
'View %s' = 'Obejrzyj %(.accusative)s'
'Deleting %(class_name)s %(instance)s would require deleting the following protected related objects: %(related_objects)s' = 'Usunięcie %(class_name.genitive)s %(instance)s może wiązać się z usunięciem następujących chronionych obiektów pokrewnych: %(related_objects)s'
'Are you sure you want to delete the %(object_name)s "%(escaped_object)s"? All of the following related items will be deleted:' = 'Czy chcesz skasować %(object_name.accusative)s „%(escaped_object)s”? Następujące obiekty powiązane zostaną usunięte:'

['Delete selected %(verbose_name_plural)s'.'gender:verbose_name_plural']
'masculine personal' = 'Usuń wybranych %(verbose_name_plural.accusative)s'
'other' = 'Usuń wybrane %(verbose_name_plural.accusative)s'

['Successfully deleted %(count)d %(items)s.'.'plurals:count']
one = 'Pomyślnie usunięto %(count)d %(items.accusative)s.'
other = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
['Successfully deleted %(count)d %(items)s.'.'plurals:count'.few.'gender:items']
'masculine personal' = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
other = 'Pomyślnie usunięto %(count)d %(items)s.'

['Add another %(verbose_name)s'.'gender:verbose_name']
'masculine inanimate' = 'Dodaj kolejny %(verbose_name.accusative)s'
'feminine' = 'Dodaj kolejną %(verbose_name.accusative)s'
'neuter' = 'Dodaj kolejne %(verbose_name.accusative)s'
other = 'Dodaj kolejnego %(verbose_name.accusative)s'

['The {name} “{obj}” was added successfully.'.'gender:name']
feminine = '{name} „{obj}” została dodana pomyślnie.'
neuter = '{name} „{obj}” zostało dodane pomyślnie.'
other = '{name} „{obj}” został dodany pomyślnie.'

['The {name} “{obj}” was added successfully. You may add another {name} below.'.'gender:name']
'masculine inanimate' = '{name} „{obj}” został dodany pomyślnie. Można dodać kolejny {name.accusative} poniżej.'
'feminine' = '{name} „{obj}” została dodana pomyślnie. Można dodać kolejną {name.accusative} poniżej.'
'neuter' = '{name} „{obj}” zostało dodane pomyślnie. Można dodać kolejne {name.accusative} poniżej.'
other = '{name} „{obj}” został dodany pomyślnie. Można dodać kolejnego {name.accusative} poniżej.'

['The {name} “{obj}” was changed successfully. You may edit it again below.'.'gender:name']
feminine = '{name} „{obj}” została pomyślnie zmieniona. Można edytować ją ponownie poniżej.'
neuter = '{name} „{obj}” zostało pomyślnie zmienione. Można edytować je ponownie poniżej.'
other = '{name} „{obj}” został pomyślnie zmieniony. Można edytować go ponownie poniżej.'

['The {name} “{obj}” was added successfully. You may edit it again below.'.'gender:name']
feminine = '{name} „{obj}” została dodana pomyślnie. Można edytować ją ponownie poniżej.'
neuter = '{name} „{obj}” zostało dodane pomyślnie. Można edytować je ponownie poniżej.'
other = '{name} „{obj}” został dodany pomyślnie. Można edytować go ponownie poniżej.'

['The {name} “{obj}” was changed successfully. You may add another {name} below.'.'gender:name']
'masculine inanimate' = '{name} „{obj}” został pomyślnie zmieniony. Można dodać kolejny {name.accusative} poniżej.'
'feminine' = '{name} „{obj}” została pomyślnie zmieniona. Można dodać kolejną {name.accusative} poniżej.'
'neuter' = '{name} „{obj}” zostało pomyślnie zmienione. Można dodać kolejne {name.accusative} poniżej.'
other = '{name} „{obj}” został pomyślnie zmieniony. Można dodać kolejnego {name.accusative} poniżej.'

['The {name} “{obj}” was changed successfully.'.'gender:name']
feminine = '{name} „{obj}” została pomyślnie zmieniona.'
neuter = '{name} „{obj}” zostało pomyślnie zmienione.'
other = '{name} „{obj}” został pomyślnie zmieniony.'

['The %(name)s “%(obj)s” was deleted successfully.'.'gender:name']
feminine = '%(name)s „%(obj)s” usunięta pomyślnie.'
neuter = '%(name)s „%(obj)s” usunięte pomyślnie.'
other = '%(name)s „%(obj)s” usunięty pomyślnie.'

['%(name)s with ID “%(key)s” doesn’t exist. Perhaps it was deleted?'.'gender:name']
feminine = '%(name)s z ID „%(key)s” nie istnieje. Może została usunięta?'
neuter = '%(name)s z ID „%(key)s” nie istnieje. Może zostało usunięte?'
other = '%(name)s z ID „%(key)s” nie istnieje. Może został usunięty?'

['%(count)s %(name)s was changed successfully.'.'plurals:count'.one.'gender:name']
feminine = '%(count)s %(name)s została pomyślnie zmieniona.'
neuter = '%(count)s %(name)s zostało pomyślnie zmienione.'
other = '%(count)s %(name)s został pomyślnie zmieniony.'

['%(count)s %(name)s was changed successfully.'.'plurals:count'.few.'gender:name']
'masculine personal' = '%(count)s %(name.genitive)s zostało pomyślnie zmienionych.'
other = '%(count)s %(name)s zostały pomyślnie zmienione.'

['%(count)s %(name)s was changed successfully.'.'plurals:count']
other = '%(count)s %(name.genitive)s zostało pomyślnie zmienionych.'

['Select all %(total_count)s %(module_name)s'.'plurals:total_count']
one = 'Wybierz %(total_count)s %(module_name)s'
['Select all %(total_count)s %(module_name)s'.'plurals:total_count'.few.'gender:module_name']
'masculine personal' = 'Wybierz wszystkich %(total_count)s %(module_name.genitive)s'
'other' = 'Wybierz wszystkie %(total_count)s %(module_name)s'
['Select all %(total_count)s %(module_name)s'.'plurals:total_count'.many.'gender:module_name']
'masculine personal' = 'Wybierz wszystkich %(total_count)s %(module_name.genitive)s'
'other' = 'Wybierz wszystkie %(total_count)s %(module_name.genitive)s'

["Deleting the %(object_name)s '%(escaped_object)s' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:".'gender:object_name']
'feminine' = 'Usunięcie %(object_name.genitive)s „%(escaped_object)s” wiązałoby się z usunięciem obiektów z nią powiązanych, ale niestety nie posiadasz uprawnień do usunięcia obiektów następujących typów:'
'other' = 'Usunięcie %(object_name.genitive)s „%(escaped_object)s” wiązałoby się z usunięciem obiektów z nim powiązanych, ale niestety nie posiadasz uprawnień do usunięcia obiektów następujących typów:'

["Deleting the %(object_name)s '%(escaped_object)s' would require deleting the following protected related objects:".'gender:object_name']
'feminine' = "Usunięcie %(object_name.genitive)s „%(escaped_object)s” wymagałoby skasowania następujących chronionych obiektów, które są z nią powiązane:"
'other' = "Usunięcie %(object_name.genitive)s „%(escaped_object)s” wymagałoby skasowania następujących chronionych obiektów, które są z nim powiązane:"

["Deleting the selected %(objects_name)s would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:".'plurals:count'.one.'gender:objects_name']
feminine = "Usunięcie wybranej %(objects_name.genitive)s spowoduje skasowanie obiektów, które są z nią powiązane. Niestety nie posiadasz uprawnień do usunięcia następujących typów obiektów:"
other = "Usunięcie wybranego %(objects_name.genitive)s spowoduje skasowanie obiektów, które są z nim powiązane. Niestety nie posiadasz uprawnień do usunięcia następujących typów obiektów:"

["Deleting the selected %(objects_name)s would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:".'plurals:count']
other = "Usunięcie wybranych %(objects_name.genitive)s spowoduje skasowanie obiektów, które są z nimi powiązane. Niestety nie posiadasz uprawnień do usunięcia następujących typów obiektów:"

["Deleting the selected %(objects_name)s would require deleting the following protected related objects:".'plurals:count'.one.'gender:objects_name']
feminine = "Usunięcie wybranej %(objects_name.genitive)s wymaga skasowania następujących chronionych obiektów, które są z nią powiązane:"
other = "Usunięcie wybranego %(objects_name.genitive)s wymaga skasowania następujących chronionych obiektów, które są z nim powiązane:"

["Deleting the selected %(objects_name)s would require deleting the following protected related objects:".'plurals:count']
other = "Usunięcie wybranych %(objects_name.genitive)s wymaga skasowania następujących chronionych obiektów, które są z nimi powiązane:"

["Are you sure you want to delete the selected %(objects_name)s? All of the following objects and their related items will be deleted:".'plurals:count'.one.'gender:objects_name']
'masculine inanimate' = "Czy chcesz skasować zaznaczony %(objects_name.accusative)s? Następujące obiekty oraz obiekty od nich zależne zostaną skasowane:"
feminine = "Czy chcesz skasować zaznaczoną %(objects_name.accusative)s? Następujące obiekty oraz obiekty od nich zależne zostaną skasowane:"
neuter = "Czy chcesz skasować zaznaczone %(objects_name.accusative)s? Następujące obiekty oraz obiekty od nich zależne zostaną skasowane:"
other = "Czy chcesz skasować zaznaczonego %(objects_name.accusative)s? Następujące obiekty oraz obiekty od nich zależne zostaną skasowane:"

["Are you sure you want to delete the selected %(objects_name)s? All of the following objects and their related items will be deleted:".'plurals:count'.other.'gender:objects_name']
'masculine personal' = "Czy chcesz skasować zaznaczonych %(objects_name.accusative)s? Następujące obiekty oraz obiekty od nich zależne zostaną skasowane:"
other = "Czy chcesz skasować zaznaczone %(objects_name.accusative)s? Następujące obiekty oraz obiekty od nich zależne zostaną skasowane:"

["Change selected %(model)s".'gender:model']
'masculine inanimate' = 'Zmień wybrany %(model.accusative)s'
feminine = 'Zmień wybraną %(model.accusative)s'
neuter = 'Zmień wybrane %(model.accusative)s'
other = 'Zmień wybranego %(model.accusative)s'

["%(count)d %(name)s".'plurals:count']
one = "%(count)d %(name)s"
other = "%(count)d %(name_plural.genitive)s"

["%(count)d %(name)s".'plurals:count'.few.'gender:name']
'masculine personal' = "%(count)d %(name_plural.genitive)s"
other = "%(count)d %(name_plural)s"
