'Cannot delete %(name)s' = 'Nie można usunąć %(name.genitive)s'
'Added {name} “{object}”.' = 'Dodano {name.accusative} „{object}”.'
'Changed {fields} for {name} “{object}”.' = 'Zmodyfikowano {fields} {name.genitive} „{object}”'
'Deleted {name} “{object}”.' = 'Usunięto {name.accusative} „{object}”.'
'Add %s' = 'Dodaj %(.accusative)s'
'Change %s' = 'Zmień %(.accusative)s'
'View %s' = 'Obejrzyj %(.accusative)s'
'Deleting %(class_name)s %(instance)s would require deleting the following protected related objects: %(related_objects)s' = 'Usunięcie %(class_name.genitive)s %(instance)s może wiązać się z usunięciem następujących chronionych obiektów pokrewnych: %(related_objects)s'
'Select %s to change' = 'Wybierz %(.accusative)s do zmiany'

'users.gender' = 'masculine personal'
'users.accusative' = 'użytkowników'
'user.accusative' = 'użytkownika'
'users.genitive' = 'użytkowników'
'group.accusative' = 'grupę'
'groups.genitive' = 'grup'
'permissions.genitive' = 'uprawnień'
'session.accusative' = 'sesję'
'sessions.genitive' = 'sesji'
'site.accusative' = 'stronę'
'sites.genitive' = 'stron'
'redirects.genitive' = 'przekierowań'
'flat page.accusative' = 'stronę statyczną'
'flat pages.genitive' = 'stron statycznych'
'log entries.genitive' = 'logów'
'content types.genitive' = 'typów zawartości'
'user.genitive' = 'użytkownika'
'group.genitive' = 'grupy'
'permission.genitive' = 'uprawnienia'
'session.genitive' = 'sesji'
'site.genitive' = 'strony'
'redirect.genitive' = 'przekierowania'
'flat page.genitive' = 'strony statycznej'
'log entry.genitive' = 'logu'
'content type.genitive' = 'typu zawartości'
'user.gender' = 'masculine personal'
'group.gender' = 'feminine'
'permission.gender' = 'neuter'
'session.gender' = 'feminine'
'site.gender' = 'feminine'
'redirect.gender' = 'neuter'
'redirect.accusative' = 'przekierowanie'
'flat page.gender' = 'feminine'
'log entry.gender' = 'masculine inanimate'
'content type.gender' = 'masculine inanimate'

['Delete selected %(verbose_name_plural)s'.'gender:verbose_name_plural']
'masculine personal' = 'Usuń wybranych %(verbose_name_plural.accusative)s'
'other' = 'Usuń wybrane %(verbose_name_plural.accusative)s'

['Successfully deleted %(count)d %(items)s.'.'gender:items'.'masculine personal'.'plurals:count']
one = 'Pomyślnie usunięto %(count)d %(items.accusative)s.'
few = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
many = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
other = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
['Successfully deleted %(count)d %(items)s.'.'gender:items'.'other'.'plurals:count']
one = 'Pomyślnie usunięto %(count)d %(items.accusative)s.'
few = 'Pomyślnie usunięto %(count)d %(items)s.'
many = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
other = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'

['Add another %(verbose_name)s'.'gender:verbose_name']
'masculine personal' = 'Dodaj kolejnego %(verbose_name.accusative)s'
'masculine animate' = 'Dodaj kolejnego %(verbose_name.accusative)s'
'masculine inanimate' = 'Dodaj kolejny %(verbose_name.accusative)s'
'feminine' = 'Dodaj kolejną %(verbose_name.accusative)s'
'neuter' = 'Dodaj kolejne %(verbose_name.accusative)s'

['The {name} “{obj}” was added successfully.'.'gender:name']
masculine = '{name} „{obj}” został dodany pomyślnie.'
'masculine inanimate' = '{name} „{obj}” został dodany pomyślnie.'
'masculine personal' = '{name} „{obj}” został dodany pomyślnie.'
feminine = '{name} „{obj}” została dodana pomyślnie.'
neuter = '{name} „{obj}” zostało dodane pomyślnie.'

['The {name} “{obj}” was added successfully. You may add another {name} below.'.'gender:name']
'masculine personal' = '{name} „{obj}” został dodany pomyślnie. Można dodać kolejnego {name.accusative} poniżej.'
'masculine animate' = '{name} „{obj}” został dodany pomyślnie. Można dodać kolejnego {name.accusative} poniżej.'
'masculine inanimate' = '{name} „{obj}” został dodany pomyślnie. Można dodać kolejny {name.accusative} poniżej.'
'feminine' = '{name} „{obj}” została dodana pomyślnie. Można dodać kolejną {name.accusative} poniżej.'
'neuter' = '{name} „{obj}” zostało dodane pomyślnie. Można dodać kolejne {name.accusative} poniżej.'

['The {name} “{obj}” was changed successfully. You may edit it again below.'.'gender:name']
'masculine personal' = '{name} „{obj}” został pomyślnie zmieniony. Można edytować go ponownie poniżej.'
'masculine animate' = '{name} „{obj}” został pomyślnie zmieniony. Można edytować go ponownie poniżej.'
'masculine inanimate' = '{name} „{obj}” został pomyślnie zmieniony. Można edytować go ponownie poniżej.'
feminine = '{name} „{obj}” została pomyślnie zmieniona. Można edytować ją ponownie poniżej.'
neuter = '{name} „{obj}” zostało pomyślnie zmienione. Można edytować je ponownie poniżej.'

['The {name} “{obj}” was added successfully. You may edit it again below.'.'gender:name']
'masculine personal' = '{name} „{obj}” został dodany pomyślnie. Można edytować go ponownie poniżej.'
'masculine animate' = '{name} „{obj}” został dodany pomyślnie. Można edytować go ponownie poniżej.'
'masculine inanimate' = '{name} „{obj}” został dodany pomyślnie. Można edytować go ponownie poniżej.'
feminine = '{name} „{obj}” została dodana pomyślnie. Można edytować ją ponownie poniżej.'
neuter = '{name} „{obj}” zostało dodane pomyślnie. Można edytować je ponownie poniżej.'

['The {name} “{obj}” was changed successfully. You may add another {name} below.'.'gender:name']
'masculine personal' = '{name} „{obj}” został pomyślnie zmieniony. Można dodać kolejnego {name.accusative} poniżej.'
'masculine animate' = '{name} „{obj}” został pomyślnie zmieniony. Można dodać kolejnego {name.accusative} poniżej.'
'masculine inanimate' = '{name} „{obj}” został pomyślnie zmieniony. Można dodać kolejny {name.accusative} poniżej.'
'feminine' = '{name} „{obj}” została pomyślnie zmieniona. Można dodać kolejną {name.accusative} poniżej.'
'neuter' = '{name} „{obj}” zostało pomyślnie zmienione. Można dodać kolejne {name.accusative} poniżej.'

['The {name} “{obj}” was changed successfully.'.'gender:name']
'masculine personal' = '{name} „{obj}” został pomyślnie zmieniony.'
'masculine animate' = '{name} „{obj}” został pomyślnie zmieniony.'
'masculine inanimate' = '{name} „{obj}” został pomyślnie zmieniony.'
feminine = '{name} „{obj}” została pomyślnie zmieniona.'
neuter = '{name} „{obj}” zostało pomyślnie zmienione.'

['The %(name)s “%(obj)s” was deleted successfully.'.'gender:name']
'masculine personal' = '%(name)s „%(obj)s” usunięty pomyślnie.'
'masculine animate' = '%(name)s „%(obj)s” usunięty pomyślnie.'
'masculine inanimate' = '%(name)s „%(obj)s” usunięty pomyślnie.'
feminine = '%(name)s „%(obj)s” usunięta pomyślnie.'
neuter = '%(name)s „%(obj)s” usunięte pomyślnie.'

['%(name)s with ID “%(key)s” doesn’t exist. Perhaps it was deleted?'.'gender:name']
'masculine personal' = '%(name)s z ID „%(key)s” nie istnieje. Może został usunięty?'
'masculine animate' = '%(name)s z ID „%(key)s” nie istnieje. Może został usunięty?'
'masculine inanimate' = '%(name)s z ID „%(key)s” nie istnieje. Może został usunięty?'
feminine = '%(name)s z ID „%(key)s” nie istnieje. Może została usunięta?'
neuter = '%(name)s z ID „%(key)s” nie istnieje. Może zostało usunięte?'

['%(count)s %(name)s was changed successfully.'.'plurals:count'.one.'gender:name']
'masculine personal' = '%(count)s %(name)s został pomyślnie zmieniony.'
'masculine animate' = '%(count)s %(name)s został pomyślnie zmieniony.'
'masculine inanimate' = '%(count)s %(name)s został pomyślnie zmieniony.'
feminine = '%(count)s %(name)s została pomyślnie zmieniona.'
neuter = '%(count)s %(name)s zostało pomyślnie zmienione.'

['%(count)s %(name)s was changed successfully.'.'plurals:count'.few.'gender:name']
'masculine personal' = '%(count)s %(name.genitive)s zostało pomyślnie zmienionych.'
'other' = '%(count)s %(name)s zostały pomyślnie zmienione.'

['%(count)s %(name)s was changed successfully.'.'plurals:count']
many = '%(count)s %(name.genitive)s zostało pomyślnie zmienionych.'
other = '%(count)s %(name.genitive)s zostało pomyślnie zmienione.'

['Select all %(total_count)s %(module_name)s'.'plurals:total_count']
one = 'Wybierz %(total_count)s %(module_name)s'
['Select all %(total_count)s %(module_name)s'.'plurals:total_count'.few.'gender:module_name']
'masculine personal' = 'Wybierz wszystkich %(total_count)s %(module_name.genitive)s'
'other' = 'Wybierz wszystkie %(total_count)s %(module_name)s'
['Select all %(total_count)s %(module_name)s'.'plurals:total_count'.many.'gender:module_name']
'masculine personal' = 'Wybierz wszystkich %(total_count)s %(module_name.genitive)s'
'other' = 'Wybierz wszystkie %(total_count)s %(module_name.genitive)s'
