['Delete selected %(verbose_name_plural)s'.gender]
'masculine personal' = 'Usuń wybranych %(verbose_name_plural.accusative)s'
'other' = 'Usuń wybrane %(verbose_name_plural.accusative)s'

['Successfully deleted %(count)d %(items)s.'.gender.'masculine personal'.plurals]
one = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
few = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
many = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
other = 'Pomyślnie usunięto %(count)d %(items.accusative)s.'
['Successfully deleted %(count)d %(items)s.'.gender.'other'.plurals]
one = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
few = 'Pomyślnie usunięto %(count)d %(items)s.'
many = 'Pomyślnie usunięto %(count)d %(items.genitive)s.'
other = 'Pomyślnie usunięto %(count)d %(items.accusative)s.'

'Cannot delete %(name)s' = 'Nie można usunąć %(name.genitive)s'
'Please enter the correct %(username)s and password for a staff account. Note that both fields may be case-sensitive.' = 'case:accusative'
'Add another %(verbose_name)s' = 'gender,case:accusative'
'Added {name} “{object}”.' = 'case:accusative (name)'
'Changed {fields} for {name} “{object}”.' = 'case:instrumental (name)'
'Changed {fields}.' = 'case:accusative'
'Deleted {name} “{object}”.' = 'case:accusative (name)'
'The {name} “{obj}” was added successfully.' = 'gender (name)'
'The {name} “{obj}” was added successfully. You may add another {name} below.' = 'gender,case:accusative (2nd name)'
'The {name} “{obj}” was changed successfully. You may edit it again below.' = 'gender (name)'
'The {name} “{obj}” was added successfully. You may edit it again below.' = 'gender (name)'
'The {name} “{obj}” was changed successfully. You may add another {name} below.' = 'gender,case:accusative (2nd name)'
'The {name} “{obj}” was changed successfully.' = 'gender (name)'
'The %(name)s “%(obj)s” was deleted successfully.' = 'gender (name)'
'%(name)s with ID “%(key)s” doesn’t exist. Perhaps it was deleted?' = 'gender (name)'
'Add %s' = 'case:accusative'